### ISSUE TITLE
One of the Python examples breaks the CI build.

### ISSUE THREAD

**Issue by pimlock** [aws-samples/aws-cdk-examples#168]
### What is the problem?

The CI build for this package is failing currently. There is a problem with building one of the Python examples with this exception:

```
TypeError: __init__() got an unexpected keyword argument 'subnetType'
```

### Verbose Log

```
==============================
building project: /home/travis/build/aws-samples/aws-cdk-examples/scripts/../python/ecs/cluster/requirements.txt
==============================

Traceback (most recent call last):
  File "app.py", line 40, in <module>
    ECSCluster(app, "MyFirstEcsCluster")
  File "/tmp/.venv/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "app.py", line 27, in __init__
    vpc_subnets={'subnetType': ec2.SubnetType.PUBLIC}
  File "/tmp/.venv/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  ...
  File "/tmp/.venv/lib/python3.6/site-packages/aws_cdk/aws_autoscaling/__init__.py", line 4152, in __init__
    if isinstance(vpc_subnets, dict): vpc_subnets = aws_cdk.aws_ec2.SubnetSelection(**vpc_subnets)
TypeError: __init__() got an unexpected keyword argument 'subnetType'
```

Full log: https://gist.github.com/pimlock/745a7fb8665dca2e6b10aabadb225786

**Comment by skinny85** [comment]
Fixed by #170 .
