### ISSUE TITLE
[cdk-eks] Error "The security token included in the request is invalid" when creating a cluster

### ISSUE THREAD

**Issue by willievu** [aws-samples/aws-cdk-examples#314]
### The Question

I am trying to create an EKS cluster using CDK.  I used the example source in https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/eks/cluster/index.ts.  At deployment, I encounter the following error.  Any ideas?

```
 32/42 | 6:46:14 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster            | Cluster/Resource/Resource/Default (Cluster9EE0221C) Failed to create resource. Error: The security token included in the request is invalid
[cdk.log](https://github.com/aws-samples/aws-cdk-examples/files/4883034/cdk.log)

    at invokeUserFunction (/var/task/framework.js:85:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Remote function error: UnrecognizedClientException: The security token included in the request is invalid
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at R
        new CustomResource (/home/ec2-user/environment/multicast-eks/cdk/node_modules/@aws-cdk/core/lib/custom-resource.ts:115:21)
        \_ new ClusterResource (/home/ec2-user/environment/multicast-eks/cdk/node_modules/@aws-cdk/aws-eks/lib/cluster-resource.ts:116:22)
        \_ new Cluster (/home/ec2-user/environment/multicast-eks/cdk/node_modules/@aws-cdk/aws-eks/lib/cluster.ts:449:18)
        \_ new MulticastEksClusterStack (/home/ec2-user/environment/multicast-eks/cdk/lib/multicast-eks-cluster-stack.ts:18:24)
        \_ Object.<anonymous> (/home/ec2-user/environment/multicast-eks/cdk/bin/multicast-eks.ts:9:1)
        \_ Module._compile (internal/modules/cjs/loader.js:778:30)
        \_ Module.m._compile (/home/ec2-user/environment/multicast-eks/cdk/node_modules/ts-node/src/index.ts:858:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        \_ Object.require.extensions.(anonymous function) [as .ts] (/home/ec2-user/environment/multicast-eks/cdk/node_modules/ts-node/src/index.ts:861:12)
        \_ Module.load (internal/modules/cjs/loader.js:653:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:585:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
        \_ main (/home/ec2-user/environment/multicast-eks/cdk/node_modules/ts-node/src/bin.ts:227:14)
        \_ Object.<anonymous> (/home/ec2-user/environment/multicast-eks/cdk/node_modules/ts-node/src/bin.ts:513:3)
        \_ Module._compile (internal/modules/cjs/loader.js:778:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        \_ Module.load (internal/modules/cjs/loader.js:653:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:585:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
        \_ findNodeScript.then.existing (/home/ec2-user/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```
Full cdk deploy log is attached.

### Environment

  - **CDK CLI Version:**   cdk version 1.49.1 (build 7d6321f).  eksctl version 0.23.0. 

kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:40:13Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
  - **Example:**  EKSCluster
  - **Example Version:**  
  - **OS:**  Amazon Linux in Cloud9
  - **Language:**  Typescript

### Other information 

I created an IAM role with AdministratorAccess and assigned it to the Cloud9 EC2 instance and also disabled Cloud9 AWS managed temporary credentials.

**Comment by richardhboyd** [comment]
You may also need to refresh the browser where your Cloud9 IDE is running to force it to pick up the instance profile credentials.

**Comment by willievu** [comment]
I did remove aws cli credentials and restart Cloud9 instance and browser.

**Comment by NGL321** [comment]
@willievu,

Sorry for the delay in response, Richard is correct that this is an issue with your AWS credentials.

Did you set up your credentials following [this guide](https://docs.aws.amazon.com/cloud9/latest/user-guide/credentials.html#credentials-permanent-create)?

If you are still running into the credential problem and you set up the credentials following the guidance from the Cloud9 docs, let me know and I can investigate further.


😸 😷
