### ISSUE TITLE
typescript/ecs/fargate-service-with-efs/lambda.js broken with too many parameters in taskdef

### ISSUE THREAD

**Issue by ralph-tice** [aws-samples/aws-cdk-examples#460]
### What is the problem?
`typescript/ecs/fargate-service-with-efs/lambda.js` passes the results of a `describeTaskDefinition` call into a `registerTaskDefinition` call which requires some parameters to be deleted.  There are two new parameters that need to be deleted.

### Reproduction Steps
Just `cdk deploy` the example.

### Verbose Log

```sh
2021-06-29T21:50:17.333Z	857787d4-0fe7-41ea-b081-f8e80099c0cb	INFO	MultipleValidationErrors: There were 2 validation errors:
* UnexpectedParameter: Unexpected key 'registeredAt' found in params
* UnexpectedParameter: Unexpected key 'registeredBy' found in params
    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:40:28)
    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:386:7)
    at /var/runtime/node_modules/aws-sdk/lib/config.js:404:9
    at EnvironmentCredentials.get (/var/runtime/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/var/runtime/node_modules/aws-sdk/lib/config.js:398:24)
    at Config.getCredentials (/var/runtime/node_modules/aws-sdk/lib/config.js:418:9) {
  code: 'MultipleValidationErrors',
  errors: [
    UnexpectedParameter: Unexpected key 'registeredAt' found in params
        at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
        at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:77:14)
        at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
        at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)
        at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
        at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
        at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9
        at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:386:7)
        at /var/runtime/node_modules/aws-sdk/lib/config.js:404:9 {
      code: 'UnexpectedParameter',
      time: 2021-06-29T21:50:17.332Z
    },
    UnexpectedParameter: Unexpected key 'registeredBy' found in params
        at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
        at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:77:14)
        at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)
        at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
        at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)
        at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
        at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
        at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9
        at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:386:7)
        at /var/runtime/node_modules/aws-sdk/lib/config.js:404:9 {
      code: 'UnexpectedParameter',
      time: 2021-06-29T21:50:17.332Z
    }
  ],
  time: 2021-06-29T21:50:17.332Z
} MultipleValidationErrors: There were 2 validation errors:
* UnexpectedParameter: Unexpected key 'registeredAt' found in params
* UnexpectedParameter: Unexpected key 'registeredBy' found in params
    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:40:28)
    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:386:7)
    at /var/runtime/node_modules/aws-sdk/lib/config.js:404:9
    at EnvironmentCredentials.get (/var/runtime/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/var/runtime/node_modules/aws-sdk/lib/config.js:398:24)
    at Config.getCredentials (/var/runtime/node_modules/aws-sdk/lib/config.js:418:9)
```

### Environment

  - **CDK CLI Version:** 1.110.0 (build 32f00eb)
  - **Example:** ecs/fargate-service-with-efs
  - **Example Version:** master
  - **OS:** OSX Mojave
  - **Language:** TypeScript

### Other information 
I have a PR with the fix to follow.

**Comment by ryparker** [comment]
Hey @ralph-tice :wave:

Thanks for bringing this to our attention and for opening a PR with the fix. I'm labeling this as p1 which means it has been prioritized as important. We'll get your PR reviewed once we have bandwidth.
