### ISSUE TITLE
https://github.com/aws-samples/aws-cdk-examples/tree/master/java/codebuild/project documentation issue

### ISSUE THREAD

**Issue by nagkumar** [aws-samples/aws-cdk-examples#745]
### Describe the bug

To run https://github.com/aws-samples/aws-cdk-examples/tree/master/java/codebuild examples bootstraping should be done in certain way, that command is not present in readme.md

### Expected Behavior

command to boot strap this project should be mentioned properly in readme.md

### Current Behavior

iac\aws\cdk\java\codebuild\project>  cdk bootstrap --trust projectStack --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://projectStack/ap-south-1
 ⏳  Bootstrapping environment aws://projectStack/ap-south-1...
 ❌  Environment aws://projectStack/ap-south-1 failed bootstrapping: Error: Need to perform AWS calls for account projectStack, but the current credentials are for 132462119873
    at SdkProvider.forEnvironment (d:\Apps\Dev\langs\scripting\js\Node\18.x\18.9.0\node_modules\aws-cdk\lib\api\aws-auth\sdk-provider.ts:184:60)
    at Function.lookup (d:\Apps\Dev\langs\scripting\js\Node\18.x\18.9.0\node_modules\aws-cdk\lib\api\bootstrap\deploy-bootstrap.ts:31:18)
    at Bootstrapper.modernBootstrap (d:\Apps\Dev\langs\scripting\js\Node\18.x\18.9.0\node_modules\aws-cdk\lib\api\bootstrap\bootstrap-environment.ts:81:21)
    at d:\Apps\Dev\langs\scripting\js\Node\18.x\18.9.0\node_modules\aws-cdk\lib\cdk-toolkit.ts:621:24
    at async Promise.all (index 0)
    at CdkToolkit.bootstrap (d:\Apps\Dev\langs\scripting\js\Node\18.x\18.9.0\node_modules\aws-cdk\lib\cdk-toolkit.ts:618:5)
    at initCommandLine (d:\Apps\Dev\langs\scripting\js\Node\18.x\18.9.0\node_modules\aws-cdk\lib\cli.ts:349:12)

Need to perform AWS calls for account projectStack, but the current credentials are for 132462119873

### Reproduction Steps

go to iac\aws\cdk\java\codebuild\project folder and run deploy it gives the above error

### Possible Solution

proper documentation in readme.md

### CDK CLI Version

'2.43.1'

### Node.js Version

18

### OS

windows 10

### Language

Java

### Language Version

jdk18

**Comment by nagkumar** [comment]
On further analysis, the answer to all this some special command to bootstrap, such command is not given in readme.md can any help what is the correct way to bootstrap these 3 examples under codebuild.

**Comment by nagkumar** [comment]
```
	IRole role =
		Role.fromRoleArn(this, "someId", "arn:partition:service:region:account-id:resource-type:resource-id");
```

Looks like this line also needs to be changed for this code to work,  looked at class `com.myorg.ProjectStack`

**Comment by kaiz-io** [comment]
Thanks for the report. The error you hit was from passing "projectStack" (a stack name) where `cdk bootstrap` expects an AWS account ID. The correct format is:

```bash
cdk bootstrap aws://123456789012/ap-south-1
```

Where `123456789012` is your actual AWS account number. You don't need `--trust` or `--cloudformation-execution-policies` for a simple single-account deploy like this example.

Regarding adding bootstrap instructions to the README - bootstrapping is a one-time prerequisite for all CDK projects, not specific to this example. The [CDK bootstrapping docs](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html) cover it in detail. Adding it to individual example READMEs would create maintenance overhead across 100+ examples.

Closing as the error was a CLI usage issue rather than a bug in the example code.
