### ISSUE TITLE
https://github.com/aws-samples/aws-cdk-examples/tree/master/java/custom-resource fails cdk ls

### ISSUE THREAD

**Issue by nagkumar** [aws-samples/aws-cdk-examples#746]
### Describe the bug

cdk ls 

should work properly

### Expected Behavior

it should not fail.. 

may be the runtime used should be python and should point to file instead of directly

### Current Behavior

software.amazon.jsii.JsiiError: Error: cannot find ./lambda/custom-resource-handler.py/index.js
@jsii/kernel.RuntimeError: Error: cannot find ./lambda/custom-resource-handler.py/index.js
    at Kernel._ensureSync (C:\Users\RAJANA~1\AppData\Local\Temp\jsii-java-runtime105214873076870085\lib\program.js:7889:27)
    at Kernel.sinvoke (C:\Users\RAJANA~1\AppData\Local\Temp\jsii-java-runtime105214873076870085\lib\program.js:7325:34)
    at KernelHost.processRequest (C:\Users\RAJANA~1\AppData\Local\Temp\jsii-java-runtime105214873076870085\lib\program.js:10466:36)
    at KernelHost.run (C:\Users\RAJANA~1\AppData\Local\Temp\jsii-java-runtime105214873076870085\lib\program.js:10429:22)
    at Immediate._onImmediate (C:\Users\RAJANA~1\AppData\Local\Temp\jsii-java-runtime105214873076870085\lib\program.js:10430:46)
    at process.processImmediate (node:internal/timers:471:21)
        at software.amazon.jsii.JsiiRuntime.processErrorResponse(JsiiRuntime.java:130)
        at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:96)
        at software.amazon.jsii.JsiiClient.callStaticMethod(JsiiClient.java:168)
        at software.amazon.jsii.JsiiObject.jsiiStaticCall(JsiiObject.java:187)
        at software.amazon.jsii.JsiiObject.jsiiStaticCall(JsiiObject.java:166)
        at software.amazon.awscdk.CustomResourceProvider.getOrCreate(CustomResourceProvider.java:79)
        at software.amazon.awscdk.examples.CustomResourceStack.<init>(CustomResourceStack.java:26)
        at software.amazon.awscdk.examples.CustomResourceApp.main(CustomResourceApp.java:9)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
        at java.base/java.lang.Thread.run(Thread.java:833)

### Reproduction Steps

just say 

mvn compile
cdk ls

### Possible Solution

na

### CDK CLI Version

2.43.1

### Node.js Version

18

### OS

windows 10

### Language

Java

**Comment by its-mirus-lu** [comment]
The java/custom-resource example should be deleted/deprecated since the [CustomResourceProvider](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudformation.CustomResourceProvider.html) is deprecated as of v2.
