### ISSUE TITLE
RDS cluster example: Cannot read property 'secretRotationApplication'

### ISSUE THREAD

**Issue by sblackstone** [aws-samples/aws-cdk-examples#91]
```/Users/sblackstone/code/xxx/yyyy/node_modules/@aws-cdk/aws-rds/lib/cluster.ts:297
    this.secretRotationApplication = props.engine.secretRotationApplication;
                                                  ^
TypeError: Cannot read property 'secretRotationApplication' of undefined
    at new DatabaseCluster (/Users/sblackstone/code/xxx/yyyy/node_modules/@aws-cdk/aws-rds/lib/cluster.ts:297:51)
    at new TafDocsProcessingStack (/Users/sblackstone/code/xxx/yyyy/lib/yyyy-stack.js:24:21)
    at Object.<anonymous> (/Users/sblackstone/code/xxx/yyyy/bin/yyyy.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
Subprocess exited with error 1```

**Comment by kaizio** [comment]
Which example does this issue occur in? I cannot find the code or this was fixed in some PR.
