### ISSUE TITLE
aws-cdk-examples/typescript/eks/cluster unsupported Kubernetes version

### ISSUE THREAD

**Issue by jaysonmc** [aws-samples/aws-cdk-examples#936]
### Describe the bug

CDK deploy (after running npm build) returns the following error:

`
Received response status [FAILED] from custom resource. Message returned: unsupported Kubernetes version

Logs: /aws/lambda/MyEKSCluster-awscdkawseksCl-OnEventHandler42BEBAE0-8lTdzZtR8u8j

at deserializeAws_restJson1InvalidParameterExceptionResponse (/var/runtime/node_modules/@aws-sdk/client-eks/dist-cjs/proto
cols/Aws_restJson1.js:2490:23)
at deserializeAws_restJson1CreateClusterCommandError (/var/runtime/node_modules/@aws-sdk/client-eks/dist-cjs/protocols/Aws
_restJson1.js:1017:25)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.j
s:51:46)
at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
at async ClusterResourceHandler.onCreate (/var/task/cluster.js:1:1084) (RequestId: ba2de978-9fa2-4f55-aaa6-bd873cdc7c7e)
`

As an aside, this project is missing a readme. 

### Expected Behavior

CDK deploy to successfully execute

### Current Behavior

CDK deploy fails with unsupported Kubernetes version

### Reproduction Steps

git clone
cd aws-cdk-examples/typescript/eks/cluster
npm run build
cdk deploy

### Possible Solution

I tried different version numbers (ex: /aws-cdk-examples/typescript/eks/cluster/index.ts line 21 changing version number to V1_27), but am getting the same error 

### CDK CLI Version

2.96.2 (build 3edd240) (cloud9 default)

### Node.js Version

v16.20.2

### OS

Amazon Linux 2 (x86-64)

### Language

Typescript

### Language Version

~5.1.6

**Comment by kaizio** [comment]
I have a fix for this. I was just going through testing the build of all typescript examples and making sure they work with the latest cdk version. Just need to setup the PRs. Will do this one now
